/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.Bill;
import GUI.Manage.CalenderWindow;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PHONG VU
 */
public class StatisticalJPanel extends javax.swing.JPanel{
    CalenderWindow  calenderWindowFrom;
    CalenderWindow  calenderWindowTo;
    /**
     * Creates new form StatisticalJPanel
     */
    public StatisticalJPanel() {
        
        initComponents();
        calenderWindowFrom = new CalenderWindow();
        calenderWindowFrom.setUndecorated(true);
        calenderWindowTo = new CalenderWindow();
        calenderWindowTo.setUndecorated(true);
//        jTFFrom.setText((new Date()).toString());
//        jTFTo.setText((new Date()).toString());
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpnRoot = new javax.swing.JPanel();
        jlbLogo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTFFrom = new javax.swing.JTextField();
        jBtnFrom = new javax.swing.JButton();
        jBtnTo = new javax.swing.JButton();
        jTFTo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnSearch = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(31, 36, 42));

        jpnRoot.setBackground(new java.awt.Color(31, 36, 42));
        jpnRoot.setPreferredSize(new java.awt.Dimension(735, 676));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Andong", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(169, 224, 49));
        jLabel7.setText("Hotel Management");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(169, 224, 49));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_DOT_100px.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(169, 224, 49));
        jLabel15.setText("HVH Soft");

        jTFFrom.setBackground(new java.awt.Color(31, 36, 42));
        jTFFrom.setForeground(new java.awt.Color(169, 224, 49));

        jBtnFrom.setBackground(new java.awt.Color(31, 36, 42));
        jBtnFrom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnFrom.setForeground(new java.awt.Color(169, 224, 49));
        jBtnFrom.setText("From");
        jBtnFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFromActionPerformed(evt);
            }
        });

        jBtnTo.setBackground(new java.awt.Color(31, 36, 42));
        jBtnTo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnTo.setForeground(new java.awt.Color(169, 224, 49));
        jBtnTo.setText("To");
        jBtnTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnToActionPerformed(evt);
            }
        });

        jTFTo.setBackground(new java.awt.Color(31, 36, 42));
        jTFTo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTFTo.setForeground(new java.awt.Color(169, 224, 49));

        jTable1.setBackground(new java.awt.Color(31, 36, 42));
        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(169, 224, 49));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Bill", "ID Customer", "ID Room", "Sum Money", "Date Check Out", "Date Check In", "Check"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setDoubleBuffered(true);
        jTable1.setSelectionBackground(new java.awt.Color(31, 36, 42));
        jTable1.setSelectionForeground(new java.awt.Color(31, 36, 42));
        jTable1.setShowGrid(false);
        jScrollPane1.setViewportView(jTable1);

        jBtnSearch.setBackground(new java.awt.Color(31, 36, 42));
        jBtnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnSearch.setForeground(new java.awt.Color(169, 224, 49));
        jBtnSearch.setText("Search");
        jBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(249, 249, 249))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnRootLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(jpnRootLayout.createSequentialGroup()
                                .addComponent(jBtnFrom)
                                .addGap(4, 4, 4)
                                .addComponent(jTFFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jBtnSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFTo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnTo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jlbLogo)
                .addGap(54, 54, 54))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addComponent(jlbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnRootLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnRootLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(1, 1, 1)))
                        .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnRootLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnFrom)
                                    .addComponent(jBtnTo)
                                    .addComponent(jTFTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jBtnSearch, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jBtnSearch.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnToActionPerformed
        calenderWindowTo.addPropertyChangeListener(new propertyChangJTFTo());
        calenderWindowTo.setLocation(jTFTo.getLocationOnScreen().x,(jTFTo.getLocationOnScreen().y + jTFTo.getHeight()));
        try {
            DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
            Date date = df.parse(jTFTo.getText().toString());
//                    DateFormat df2 = new SimpleDateFormat("MM/dd/yyyy");
//                    String dateStringd  = df2.format(date);
            Date selectDate = date;
            calenderWindowTo.resetSelection(selectDate);
        } catch (Exception e) {
        }
        
        calenderWindowTo.setVisible(true);
    }//GEN-LAST:event_jBtnToActionPerformed
    
    private void jBtnFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFromActionPerformed
        calenderWindowFrom.addPropertyChangeListener(new propertyChangJTFFrom());
        calenderWindowFrom.setLocation(jTFFrom.getLocationOnScreen().x,(jTFFrom.getLocationOnScreen().y + jTFFrom.getHeight()));
        try {
            DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
            Date date = df.parse(jTFFrom.getText().toString());
//                    DateFormat df2 = new SimpleDateFormat("MM/dd/yyyy");
//                    String dateStringd  = df2.format(date);
            Date selectDate = date;
            calenderWindowFrom.resetSelection(selectDate);
        } catch (Exception e) {
        }
        calenderWindowFrom.setVisible(true);
        
    }//GEN-LAST:event_jBtnFromActionPerformed

    private void jBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchActionPerformed
        try {
            DefaultTableModel tableModel = (DefaultTableModel)jTable1.getModel();
            tableModel.setRowCount(0);
            ArrayList<Bill> list = BLL.BLL_BILL.getInstance().getListBillByDate(jTFFrom.getText(), jTFTo.getText());
            for(Bill b : list){
                DateFormat df2 = new SimpleDateFormat("MM/dd/yyyy");
                String dateIn  = df2.format(b.getDateCheckIn());
                String dateOut  = df2.format(b.getDateCheckOut());
                Object[] objects = {b.getIdBill(),b.getIdCustomer(),b.getIdRoom(),b.getSumMoney(),
                        dateIn,dateOut,b.getCheck()};
                tableModel.addRow(objects);
            } 
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jBtnSearchActionPerformed
    public class propertyChangJTFFrom  implements PropertyChangeListener{
        @Override
        public void propertyChange(PropertyChangeEvent evt) {
            if(evt.getPropertyName().equals("selectedDate")){
                System.out.println(evt.getNewValue());
                java.util.Calendar cal = (java.util.Calendar)evt.getNewValue();
                Date setDate = cal.getTime();
                DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
                jTFFrom.setText(df.format(setDate));
            }
        }
    }
    public class propertyChangJTFTo  implements PropertyChangeListener{
        @Override
        public void propertyChange(PropertyChangeEvent evt) {
            if(evt.getPropertyName().equals("selectedDate")){
                java.util.Calendar cal = (java.util.Calendar)evt.getNewValue();
                Date setDate = cal.getTime();
                DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
                jTFTo.setText(df.format(setDate));
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnFrom;
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JButton jBtnTo;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFFrom;
    private javax.swing.JTextField jTFTo;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlbLogo;
    private javax.swing.JPanel jpnRoot;
    // End of variables declaration//GEN-END:variables

    
}
